[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wcc_etc"
version = "0.6.0"
authors = [
  {name = "Gudmundur Stefansson", email = "gstefansson@schmidtsciences.org"},
  {name = "Mickael Rigault", email = "m.rigault@ip2i.in2p3.fr"},
  {name = "Sanchit Sabhlok", email = "ssabhlok@arizona.edu"},
  {name = "Aaron Goldtooth", email = "gold1992@arizona.edu"},
]
maintainers = [
  {name = "Gudmundur Stefansson", email = "gstefansson@schmidtsciences.org"}
]
description = "Exposure Time Calculator for the WCC."
readme = "README.md"
license = { text = "GNU GENERAL PUBLIC LICENSE - Version 3" }
requires-python = ">=3.11"
dependencies = [
  "synphot",
  "numpy",
  "astropy",
  "matplotlib",
  "pandas",
  "bokeh>=3.6",
  "flask",
  "toml",
  "tifffile",
  "photutils",
  "lazuli-transit",
]

[project.optional-dependencies]
lightcurve = ["lazuli-transit[batman]"]
exoarchive = ["lazuli-transit[archive]"]
docs = [
  "sphinx>=7",
  "sphinx-rtd-theme>=2.0",
  "nbsphinx>=0.9",
  "ipykernel",
  "myst-parser",
]
dev = [
  "pytest",
  "pre-commit",
  "ruff",
  "mypy",
]

[project.urls]
Homepage = "https://github.com/schmidt-observatories/wcc-etc"
Repository = "https://github.com/schmidt-observatories/wcc-etc"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"wcc_etc" = [
  "data/astr_obj_models/stars/pickles_models/dat_uvk/*.fits",
  "data/astr_obj_models/galaxies/brown/*",
  "data/astrophysics/*",
  "data/config/*",
  "data/sensors/**",
  "data/throughput/*",
  "data/throughput/other_filters/*",
  "data/flats/*",
  "data/psfs/*",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
src = ["src"]
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
