# config.toml
# Configuration file for the WCC ETC

#########################################################
#########################################################
# Telescope Parameters
#########################################################
[telescope]
diameter_primary = 3.065 # m
f_num = 15.0 # unitless
# Mirror coatings
path_m1_coating = ""
path_m2_coating = ""
path_m3_coating = ""
path_m4_coating = ""
# Filter choice
#path_filter = "../data/support_data/filters/sdss_r_005_syn.fits"
path_filter = ""
#path_filter = "../data/support_data/filters/SLOAN_SDSS.gprime_filter.txt"
#path_filter = "../data/support_data/filters/sdss_i_005_syn.fits"
#path_total_throughput = "../data/support_data/throughput/Lazuli_WCC_r_20250820/Lazuli_WCC_r_20250820_throughput.csv"
path_total_throughput = "../data/support_data/throughput/Lazuli_WCC_halpha_20251010_eol_qCMOS/Lazuli_WCC_halpha_20251010_eol_qCMOS_throughput.csv"
#########################################################

#########################################################
#########################################################
# Detector parameters
# Notes: 
# - Gain, dark, read and well-depth are all estimated 
#   from interpolating the .csv tables using the 'gain_setting' parameter
#########################################################
[detector]
pixel_size = 4.6 # micron / pix
read_noise = 0.56 #0.28 # e/pix, doubling to be conservative, as haven't implemented non-linearity noise
dark_current = 0.05 # e/pix/s, confirmed from Gabor, measured at -20C at MIT, now setting as 0.05 e/pix/s for 0C
gain = 0.112 # ADU/e # NOTE: Gabor's note suggest gain is ADU/e rather than e/ADU. Ask
sensor_temp = 0.0 # C, NOTE: Gabor's note suggest temp is -20C. Now assuming 0.05 e/pix/s at 0C
sensor_area = 199.69081344 # mm2: (18.8416 mm * 10.5984 mm = mm2)
well_depth = 7000 # e/pix
#gain_setting = 100 # 0.1 db
#path_dark_current = "../data/support_data/sensors/ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Dark_Current_vs_Sensor_Temperature.csv"
#path_gain_curve =   "../data/support_data/sensors/ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Gain_vs_Gain_Setting.csv"
#path_read_noise =   "../data/support_data/sensors/ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Read_Noise_vs_Gain_Setting.csv"
#path_well_depth =   "../data/support_data/sensors/ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Well_Depth_vs_Gain_Setting.csv"
path_qe = "" #../data/support_data/sensors/qCMOS/qCMOS_QE.csv"
#temp_stability = '0.1Kelvin/hour' # WAG
#########################################################

#########################################################
#########################################################
# Astrophysical Parameters
#########################################################
[zodi]
zodi_mag_r=22.5 #  L3-0016 has v-band mag of 22.1. Need trace of where 22.5 originates from.
#########################################################

# Systematic error sources
